### ISSUE TITLE
Interface/Icons look broken, UI issues

### ISSUE THREAD

**Issue by schniepp** [PhieF/CarnetNextcloud#4]
I just tested this in NC 14 for the first time. 

There are several issues with the UI.

1. First of all, the icon of the app itself appears to be broken. 
2. Then, there are three more broken icon on the page once the app is started/clicked. 
3. In addition, parts of the delete button appear for a second time.
4. It also was not clear to me where to set the folder for the carnet files, but perhaps this is just not showing up because of broken interface issues?

Let me know if any further info is needed. Browser is the latest stable chrome, client platform is Linux_amd64.

**Comment by AaronADev** [comment]
@schniepp Hello there - 

I have addressed this issue already here Carnet App Icon Missing and OCP\Lock\LockedException Errors #2, this is a duplicate. 

Can you continue addressing this issue there, I provided some logs that were output when the application was installed. And, some of my problems occured due to my instance being a Snap but there are many snap users for NC nowadays so I would imagine it is pretty urgent for that to be addressed.

@PhieF Can we take a look at this sometime soon, there are also some other issues I am going to bring up in a separate issue. Thanks

**Comment by schniepp** [comment]
Thanks! OK, I will report there if you think it is the same reason. In my case, it is not only the main icon of the app, but also several other UI issues.

**Comment by adocampo** [comment]
Same here, interface completely unusable, you cannot create, delete or nothing
![imagen](https://user-images.githubusercontent.com/2266612/46602886-c7093a80-caf1-11e8-85a3-7b5652508976.png)

On the other hand, Carnet Icon shows fine here.
![imagen](https://user-images.githubusercontent.com/2266612/46602970-02a40480-caf2-11e8-86dc-76a5c48e31e2.png)

NC: 13.0.6 stable
Firefox 62.0.3
Arch Linux

**Comment by PhieF** [comment]
Hm ok really not good, I'm having a look, thanks for reporting

**Comment by adocampo** [comment]
https://cloud.docampo.net/css/core/5b44-457d-server.css?v=0314adf3

**Comment by PhieF** [comment]
Well I'm more looking for design.css if possible, this one isn't mine :P

**Comment by schniepp** [comment]
In my case, the broken interface looks exactly as reported by @adocampo. 

By the way, this is what I have in nextcloud/apps/carnet/templates/CarnetElectron/browsers/design.css:
`
.demo-card-wide.mdl-card {
    min-height: 0px;
    margin: 5px;
    cursor: pointer;
}


.mdl-card__supporting-text {
    padding-bottom: 0px !important;
    box-sizing: content-box !important;
}

.note-card-view :hover,
.folder-card-view :hover {
    background-color: rgb(230, 230, 230);
    -webkit-transition: background-color 250ms linear;
    -ms-transition: background-color 250ms linear;
    transition: background-color 250ms linear;
    cursor: pointer;
}


.demo-card-wide>.mdl-card__title {
    color: black;
}

.packery-drop-placeholder {
    outline: 3px dashed #444;
    outline-offset: -6px;
    /* transition position changing */
    -webkit-transition: -webkit-transform 0.2s;
    transition: transform 0.2s;
}

/* highlight drag & drop */

/* jQuery UI Draggable adds ui-draggable-dragging */

.ui-draggable-dragging,
.is-positioning-post-drag {
    background: #C90;
    z-index: 20000 !important;
    /* keep dragged item on top */
}

.demo-card-wide>.mdl-card__menu {
    color: #fff;
}

body {
    background: #fafafa;
    position: relative;
}

#page-content {
    position: relative;
    margin: 0 auto;
}

#page-container {
    background: #fafafa;
}

#grid-container {
    margin: 0 auto;
    position: absolute;
    width: 100%;
    height: 100%;
    overflow-y: auto;
}

.big-text {
    font-size: 40px;
}

.medium-text {
    font-size: 30px;
}

@media (min-width: 1314px) {
    #grid-container {
        max-width: 1074px;
        left: calc(50% - 537px);
    }
}

.card-title {
    font-size: 24px;
    font-weight: 300;
    line-height: normal;
    color: black;
    margin: 0px;
}

.card-text {
    line-height: initial;
    margin-bottom: 10px;
    margin-right: 20px;
    word-wrap: break-word;
    color: rgba(0, 0, 0, .87);
}

.card-title:hover {
    background: none;
}

.card-text:hover {
    background: none;
}

.mdl-layout__header {
    -webkit-app-region: drag;
}

.mdl-layout__header .mdl-layout__drawer-button,
.mdl-layout__header button,
.mdl-layout__header .mdl-textfield {
    -webkit-app-region: no-drag;
}

.folder-icon {
    width: 50px;
}

.card-more-button {
    right: 0px;
    background: inherit !important;
    position: absolute !important;
}

.keywords {
    margin-bottom: 16px;
}

.keyword {
    margin-right: 3px;
    margin-top: 3px;
    padding: 3px;
    background: #D2D2D2;
    display: inline-block;
}

.card-rating {
    margin-right: 10px;
    float: right;
}

.card-medias {
    margin-left: -20px;
    margin-right: -5px;
    background: black;
    border-radius: 2px;
}

.card-medias img {
    width: 100%;
}

#contextual-dialog .mdl-button {
    padding: 0 5px;
}


#firstrun {
    display: none;
    position: relative;
    margin: auto;
    top: 50%;
    margin-top: -270px;
    max-width: 500px;
    max-height: 500px;
    padding: 10px;
    height: calc(100% - 20px);
    width: calc(100% - 20px);
    background: rgb(63, 81, 181);
    box-shadow: 0px 0px 10px grey;
    overflow-y: auto;
}



@media (max-width: 600px) {
    #firstrun {
        top: 0;
        margin-top: 0;
        max-width: 100%;
        max-height: calc(100% - 20px);
        overflow-y: auto;
    }
}
`

**Comment by AaronADev** [comment]
@PhieF Looks like there are resources that are not able to be found by the browser, Firefox and Chrome. 

These exports and references are not loading with the page view for some reason.

```js
note.js - exports.Note = Note
note-opener.js - var JSZip = require('jszip');
NoteUtils.js - exports.NoteUtils = NoteUtils
Keywords_db_manager.js - exports.RecentDBManager = RecentDBManager;
file_utils,js - exports.FileUtils = FileUtils;
```
So, it looks like this was made with electron? Some of the CSS might not be working properly because these js resources are not available to their particular views...not entirely sure, haven't had enough time to research fully.

@adocampo @schniepp What do you guys think?

**Comment by PhieF** [comment]
@schniepp thanks, did you get this from firefox or from your hard drive ? My main idea is that the url to the css file is incorrect

I've just pushed a new version with better code to handle path, perhaps it fixes your issue, can you update to 0.8.4 ?

@AaronADev 
No I guess the css file isn't loading at all, yep it was from electron, I'm getting rid of these exports but I have to maintain the electron version also, but it should work even with these errors

**Comment by adocampo** [comment]
> Well I'm more looking for design.css if possible, this one isn't mine :P

Sorry!

My Firefox cannot see design.css by any  means.  See on the picture just above the code inspector, where it says `"La hoja de estilos no puede ser cargada. https://cloud.docampo.net/apps/carnet/net/templates/CarnetElectron/browsers/design.css"`

That file is indeed on the hard drive and it's the same @schniepp 

Besides, it seems there are several problems
![imagen](https://user-images.githubusercontent.com/2266612/46614471-385ae480-cb16-11e8-9bc3-3c4276eed573.png)

I must say this nextcloud instance is a docker container, accessed through an apache reverse proxy. I have no other problems with any other nextcloud app, and I have plenty of them, so I'm pretty sure is not apache's fault. But I think it worth to mention it.

**Comment by PhieF** [comment]
OK there is indeed an issue with the path, it should be /apps/carnet/templates/

have you tried with the new version I've just sent ?

**Comment by adocampo** [comment]
> OK there is indeed an issue with the path, it should be /apps/carnet/templates/
But I have all 3rd party apps on apps2 folder... 
I can see the desing css on the URL
https://cloud.docampo.net/apps2/carnet/templates/CarnetElectron/browsers/design.css

> have you tried with the new version I've just sent ?
Nope, let me see...

**Comment by adocampo** [comment]
Problem still here. I've upgraded to 0.8.4 On Chrome, icon doesn't show like in Firefox, but I can see the design.css file
![imagen](https://user-images.githubusercontent.com/2266612/46616834-aeae1580-cb1b-11e8-8f56-b16eab7a5a48.png)

As I say, it points to apps2, not to apps. I guess that's not the problem, didn't I?

**Comment by PhieF** [comment]
can you give me the url of material.indigo-pink.min.css ?
As well as its error ?

**Comment by PhieF** [comment]
If you don't have time you can create me a test account on your server if you want

**Comment by adocampo** [comment]
I've created you an account PhieF | PhieF.psw
I can see the error is blocked:csp? 
![imagen](https://user-images.githubusercontent.com/2266612/46617560-55df7c80-cb1d-11e8-853d-6491cc33188a.png)

I think it would be better if you take a look by yourself ;)

**Comment by schniepp** [comment]
For me, 0.8.4 has solved the UI issues. It's working now on both Chrome and Firefox.

I do see another issue, however. I am guessing it is another issue, which I will report separately: I have one note that was created via Android client. The note shows up as expected. However, when I click on it, it looks like a second instance of nextcloud is running as a (html) frame of the first instance: I see a complete second bar with all the app icons. The actual note never shows up. There is a spinning wheel in the center of the page suggesting that the page is still loading, but it does not show up, even after minutes. The same thing happens when I click the button to create new carnet note in Nextcloud.

**Comment by PhieF** [comment]
Well that's the problem I have with @adocampo 's server. Is your nextcloud also in a docker ?

**Comment by adocampo** [comment]
Which config, nextcloud config?

> Grmpf it works here, at least for design, even if some other stuffs are not working like the editor. Do you know if your config is blocking direct access to php / woff2 files in apps2 folder ?

My nextcloud relevant configuration would be
```  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),
```

**Comment by schniepp** [comment]
> Well that's the problem I have with @adocampo 's server. Is your nextcloud also in a docker ?

If you are asking about my server, I have installed from the vanilla NC v14 *.zip file, so no docker or snap being used. Currently updated to the latest stable version 14.0.1. My server is running php7.1.

**Comment by adocampo** [comment]
@schniepp are your NC behind a reverse proxy like mine?

**Comment by AaronADev** [comment]
@adocampo mine isn't behind a reverse proxy, it's on a server by itself with a dedicated ip/domain. I am assuming this all has something to do with how the paths are for some of the files, snaps have a little bit of a different directory structure than standard installations. If this isn't worked out by the time I get off work I'll do some in depth troubleshooting with you guys.

**Comment by adocampo** [comment]
Ok, I just wanted to discard some rewrite rules on the reverse proxy. I doubted it was the culprit, because this is the only app failing, but If both of your NC instances are published directly, I think we can safely discard this possibility.

**Comment by PhieF** [comment]
To access the ditor I'm bypassing nextcloud because on my servers it was faster. I will try to implement editor in a more usual way and it should fix @schniepp issue.

@adocampo I've been using your server and... everything except editor (as schniepp) is working fine... can you confirm ?

**Comment by PhieF** [comment]
Question to @schniepp are you using nginx ?

**Comment by schniepp** [comment]
No, I am on apache (v. 2.4.29).
This is also a dedicated IP, dedicated domain.

**Comment by PhieF** [comment]
@schniepp can you replace carnet folder with this one 
[carnet-nc-v0.8.5.zip](https://github.com/PhieF/CarnetNextcloud/files/2456745/carnet-nc-v0.8.5.zip)

it should be on your nextcloudfolder/apps/carnet

or if like adocampo perhaps in apps2

**Comment by schniepp** [comment]
Not yet fixed. However, the behavior is slightly different. 
Now, I see _sometimes_ something that looks like an editor window (with formatting buttons/icons) for a split second, and then I see the blue ribbon showing the "FORMAT EDIT MEDIA TOOLS" options. However, the bar appears to be inactive (shown in lighter blue than it should be for an active bar).
The frame-in-page thing is gone (the one showing a second nextcloud app icon bar).

**Comment by schniepp** [comment]
Forgot to mention: tested on Chrome, Firefox, and Opera. All look pretty much identical.

**Comment by schniepp** [comment]
Oh, and, of course, the main problem remains: the page never seems to finish loading. The spinning wheel in the center keeps spinning for minutes. That might the only remaining real issue. The rest of the UI looks sane (except for being inactive, probably because it stays in "not yet finished loading" mode.

**Comment by PhieF** [comment]
OK, so the editor is loaded, but not the note

could you please open firefox dev tools for example, (f12) go to network tab, create a new note, then on th "file" column, usually at the end, you should see something beggining with open?path=
is the state 200 ?
select the line and on the right select the "response" tab, can you send me what you have ? 

Thanks again

**Comment by schniepp** [comment]
Actually, I am getting a 403:

`HTTP/1.1 403 Forbidden
Date: Mon, 08 Oct 2018 16:41:49 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
Content-Length: 241
Keep-Alive: timeout=5, max=96
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1`

**Comment by schniepp** [comment]
I guess the assigned filename is as expected:
`open?path=untitled%201.sqd`

**Comment by PhieF** [comment]
and what is the complete request url ? (first tab on the right of the console after selecting the line with open?path=)

**Comment by schniepp** [comment]
`.../index.php/apps/carnet//note/open?path=untitled 1.sqd`

The `...` is the root of my server, which I left out for privacy purposes.
I might have switched on a setting to do "pretty URLs" (config.php setting).

**Comment by schniepp** [comment]
OK, but I think it's the wrong URL used by the app. There should be an `/owncloud/` before the `index.php`, based on where my NC installation is based. That would explain the 403 error.

**Comment by adocampo** [comment]
> @adocampo I've been using your server and... everything except editor (as schniepp) is working fine... can you confirm ?

Sorry, I've just arrived home from work. I'm having the same issues both with Firefox and Chrome... I've already deleted the cache on both browsers.

**Comment by PhieF** [comment]
OK so you don't seem to have the problem but it might be the pretty url thing because it used to rely on a relative path
I can't test 'overwrite.cli.url' => 'http://localhost',
doesn't seem to work on localhost
but I've changed how the api is called, if you want to try...

[carnet-nc-v0.8.5.zip](https://github.com/PhieF/CarnetNextcloud/files/2456961/carnet-nc-v0.8.5.zip)

**Comment by schniepp** [comment]
It works now!

The functionality is there now. Editor is invoked, notes are saved, and I can re-open them. 
However, at the bottom of the web page, there is a notification saying 
`Error occured: Uncaught TypeError: fullDB is not iterable`

**Comment by adocampo** [comment]
No luck either. On Applications it says its version 0.8.4, but I guess it should be merely aesthetical. Now , clicking on the right bottom button, appears this
![imagen](https://user-images.githubusercontent.com/2266612/46626567-09556a80-cb38-11e8-9e9c-813b3061f122.png)
But I can't do nothing:nor clicking on any button, nor nothing. By refreshing the page appear this
![imagen](https://user-images.githubusercontent.com/2266612/46626635-34d85500-cb38-11e8-9b2d-53c5e6efd851.png)
Those images are in Chrome, in Firefox, is more or less the same
![imagen](https://user-images.githubusercontent.com/2266612/46626707-6a7d3e00-cb38-11e8-96d0-ae864fc9b83b.png)
Notice, but, the Carnet icon on the top menu, it continues appearing in Firefox, but not in chrome... weird.

**Comment by PhieF** [comment]
@adocampo really weird, I'm using it with the account you've created me on your server and now even the editor works

could you please reopen your dev tools and look for material.indigo-pink.min.css in network to see if it's still not found ?

**Comment by PhieF** [comment]
@schniepp is this bug in the editor ?

**Comment by adocampo** [comment]
It's *very* weird... as your user seems to work, I tried with a little browser called Min (based on Chromium), and there... it works... :|
![imagen](https://user-images.githubusercontent.com/2266612/46628278-55ef7480-cb3d-11e8-98d4-76d389ea6213.png)

Then, I tried with your user on my Chrome, and...also works
![imagen](https://user-images.githubusercontent.com/2266612/46628333-86371300-cb3d-11e8-97fe-34cdd759b59e.png)

After this, I re-logged with my account and it works!
![imagen](https://user-images.githubusercontent.com/2266612/46628481-fe9dd400-cb3d-11e8-8ee8-3dfe522f246b.png)



But not in Firefox...
![imagen](https://user-images.githubusercontent.com/2266612/46628387-a797ff00-cb3d-11e8-808f-bd8acec86c2e.png)

So, I'm totally confussed... I guess Firefox must have a super resilient cache... I'm going to do some checks, as now it works under Chrome. 
Do it work for you in Firefox, don't it?

**Comment by PhieF** [comment]
it works on my firefox with your server
try in private ? 
You still have icon issues, though, but it's "fixable"

**Comment by schniepp** [comment]
Regarding the reproducibility issues that @adocampo has observed: this could be a browser cache problem. I have seen similar problems with CSS files, etc. You could try a harder reload (Ctrl+Shift+R in Chrome). This would explain why it works on other browsers and for other users. Another thing you could try is open an incognito (private) window.

**Comment by schniepp** [comment]
@PhieF : the `Error occured: Uncaught TypeError: fullDB is not iterable` appears in a little black message box in bottom center of the browser window. I would say that technically it is the area of the window that is occupied by the editor, yes. 

It happens 100% of the time.

**Comment by PhieF** [comment]
@schniepp if you want you can send me a screenshot of the console tab of the dev tools, where the same error should appear (I think it's when you open the editor

**Comment by schniepp** [comment]
![screenshot](https://user-images.githubusercontent.com/29638213/46636105-c8078f80-cb24-11e8-9ec7-3cd8faa0256c.png)

**Comment by schniepp** [comment]
Does this work? I got this from `Console`.

**Comment by PhieF** [comment]
@schniepp OK that's not important, it's just that you have no keyboard so... db is null. It's bad programming but shouldn't lead to a bug, I guess. I will send a fix but I'd like not to modify js part a lot before finishing upgrading the electron version

@adocampo keep us in touch, your problem is... weird. Private nav also bugs ?

**Comment by schniepp** [comment]
@PhieF I suppose you mean "keywords" instead of "keyboard"? 
So how would I get a keywords database?

**Comment by adocampo** [comment]
Well, after dealing with it in my work, I find what the problem is. I saw it happens just like in my home. With http works but it doesn't works with https. if you put cloud.docampo.net, it doesn't redirect automatically to https://cloud.docampo.net I do not know why exactly, it should redirect automatically. 
The case is in chrome works because it doesn't do the redirection. Creating a new firefox profile on firefox and putting the URL without https, it also works. Putting it back to https, stop working, both in firefox and chrome.

@PhieF which protocol did you use? Perhaps http? I think @schniepp uses https, so perhaps is really something on my reverse proxy, I'm going to take a look to it

**Comment by PhieF** [comment]
Please try this :)
[carnet-nc-v0.8.6.zip](https://github.com/PhieF/CarnetNextcloud/files/2462426/carnet-nc-v0.8.6.zip)
